version: '2'
services:
  robot:
    build: .
    image: rosev3-robot
    networks:
      rosnet:
        ipv4_address: 192.168.1.111
    extends:
      file: "../master/docker-compose.yml"
      service: master
    container_name: robot
    hostname: 192.168.1.111
    working_dir: /home/ros/catkin-ws/src/ev3_launch/launch
    command: bash -c "roslaunch ./motors.launch ev3_hostname:=ev3dev"
    environment:
      - ROS_MASTER_URI=${MASTER_URI}

networks:
  rosnet:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
