version: '2'
services:
  master:
    build: .
    image: rosev3-master
    container_name: master
    hostname: master
    networks:
      rosnet:
        ipv4_address: 192.168.1.128
    extra_hosts:
      - "ev3dev:192.168.0.29"
    environment:
      - "ROS_MASTER_URI=http://master:11311"
    command: roscore -v
